### ISSUE TITLE
get database instead of create

### ISSUE THREAD

**Issue by xionglun** [google/lovefield#90] opened 2015-09-25 05:47 UTC
I  cannot find any document that explain how to get an existing db, all examples like below
```javascript
// SQL equivalent: CREATE DATABASE todo
var schemaBuilder = lf.schema.create('todo', 1);
```

Do I have to create it every time?

**Comment by arthurhsu** [comment] 2015-09-25 06:04
You are creating schema every time, not the database. Please redirect usage questions to our public forum.

Duplicate of https://github.com/google/lovefield/issues/58

**Closed by arthurhsu** 2015-09-25 06:04 UTC
