### ISSUE TITLE
sync with remote db

### ISSUE THREAD

**Issue by JosePedroDias** [google/lovefield#48] opened 2015-06-02 16:09 UTC
Any plans on integrating or even discussing best practices on integrating the browser db powered by lovefield with a remote database?

**Comment by freshp86** [comment] 2015-06-02 17:02
We are looking into this. One approach we are exploring is using Firebase under the covers, such that we leverage Firebase's syncing mechanism. There are still a few issues to solve before declaring this approach as a "best practice".

There is an example of how to sync from a server. Our performance dashboard (available at http://google.github.io/lovefield/dashboard/src/dashboard.html), is syncing with a server to display latest perf data. This syncing is only one way though (server -> client), since the data is never modified in the client. You can see specifics of how syncing is done at https://github.com/google/lovefield/blob/master/tools/dashboard/src/sync_service.js, but in a nutshell the server supports a "get updates since timestamp" query. The client detects last sync date, and requests updates since that date from the server, and in response inserts new data in the DB.

**Comment by arthurhsu** [comment] 2015-07-08 23:40
After some investigation I'd like to close this as won't fix.

I believe the "remote sync" you're talking about here is via single source of truth approach, which means there's a server (e.g. Oracle, Firebase, MongoDB, ...) that acts as the single source of truth, and all clients smartly sync with that server DB, ideally caching the data locally and sync with remote.

The problem is that the server technologies are so wildly different w.r.t.
1. Lock model and two-phase commit
2. Network latency: will it be bad enough that my local transaction will take forever to commit?
3. Data planning: what is the most efficient way to store/index/retrieve my data?

Lovefield is currently equipped with simplest features that will enable developers to write adapting layer for external data stores (see Firebase related code in lib/backstore). However, we were not able to provide a general enough "best practice" suggestion given the vast difference of server-side DB behaviors.

**Closed by arthurhsu** 2015-07-08 23:40 UTC
