### ISSUE TITLE
functions returning non standard promises

### ISSUE THREAD

**Issue by digital-synapse** [google/lovefield#79] opened 2015-09-14 02:05 UTC
Great work guys. One problem I noticed was that everything is returning a goog.Promise which has functions called .then(), .thenCatch(), and thenVoid() however the typescript definition file included with the npm package is using the es6 Promise which just has .then() and .catch()

basically, i wasnt able to catch an error and roll back a transaction because i get the runtime error "foo.catch() is not implemented"

**Comment by arthurhsu** [comment] 2015-09-14 02:24
Don't understand your issue. By design Lovefield uses *only* then(), and catch() has no effects of its operation. There are three ways to create a transaction in Lovefield:

db.insert().into(t).values(...).exec().then(function()) {
  // Implicit transaction, if anything failed, it automatically rolls back.
});

var t1 = db.createTransaction();
t1.exec([q1, q2]).then(function(results) {
  // Auto-commit explicit transaction. If anything failed, it automatically rolls back.
});

// Explicit transaction. Anything in the then() chain failed will cause transaction to rollback.
var t2 = db.createTransaction();
t2.begin().then(function() {
  // Callback only after transaction successfully begin
  return t2.attach(q1);
}).then(function() {
  // Callback only after q1 is successfully executed in memory
  return t2.attach(q2);
}).then(function() {
  return t2.commit();
}).then(function() {
  // Callback only after transaction committed, i.e. diffs flushed to data store
});
// Any error in transaction will cause an lf.Exception be raised and you need to try-catch them.
// The transaction is already rolled back when you got an lf.Exception.

So what do you mean by "catch an error and roll back a transaction"? Transactions will only keep going if and only if there is no exception. If you want to explicitly roll back a transaction because an error of somewhere else (E.g. XHR error), use explicit transaction and call t2.rollback() if such thing happens.

**Comment by digital-synapse** [comment] 2015-09-14 02:52
Thanks. I was not aware of the automatic rollback. The problem seems to be that .catch is not implemented. If this is by design then we need to replace the type definitions for Promise with goog.Promise i think. Here is an example code which produces the error

    db.insertOrReplace().into(table).values(rows).exec()
        .then(r=>{ console.log('has results!'); })
        .catch(e=>{ console.log('some error happened!');})

result:
    Uncaught TypeError: db.insertOrReplace(...).into(...).values(...).exec(...).then(...).catch is not a function

**Comment by arthurhsu** [comment] 2015-09-14 04:31
I see. Promise interface is actually preferred over goog.Promise, and the reason for using goog.Promise is mainly IE-compatibility.

**Comment by arthurhsu** [comment] 2015-09-14 05:57
BTW it's still recommend to do something like this

```js
try {
  db.insertOrReplace().into(table).values(rows).exec().then(r=>{ // commit; });
} catch(e) {
  // handle e here
}
```

Lovefield can throw at different points (e.g. syntax errors can be thrown before exec()). Using only catch does not guarantee to deal with all exceptions.

**Comment by freshp86** [comment] 2015-09-14 17:22
You should be able to make it work with typescript using catch() only. catch() accepts two functions, as follows.

```
var onSuccess = function() {...};
var onError = function() {...};
db.select().from(table).exec().then(onSuccess, onError);
```

Having said that, we can probably modify the goog.Promise to have a catch() method (it will just be an alias for thenCatch), such that the Typescript type annotations are accurate.

**Closed** 2015-09-14 21:41 UTC
