### ISSUE TITLE
Trying to reinitialize the schema every time, getting 201 error

### ISSUE THREAD

**Issue by padmavati** [google/lovefield#148] opened 2016-04-21 11:27 UTC
We are doing this as a part of background web-worker. 

```
    var LOVEFIELD_DB_CONFIG = {
        storeType : lf.schema.DataStoreType.INDEXED_DB,
        onUpgrade: function (rawDb) {
           //upgrade logic goes here
        return rawDb.dump();
    };

   this.databasePromise = null;

    this.initSchema = function () {
        if(this.databasePromise === null ) {
            var schemaBuilder = lf.schema.create("testDB", 2);
            createTable(schemaBuilder, "names");
            this.databasePromise = schemaBuilder.connect(LOVEFIELD_DB_CONFIG);
        }

        return this.databasePromise;
    };

    this.reinitSchema = function() {
        this.databasePromise = null;
        return this.initSchema();
    };`
```

Trying to reinitialize the schema getting the  following error
[http://google.github.io/lovefield/error_lookup/src/error_lookup.html?c=201](url)

**Comment by freshp86** [comment] 2016-04-21 17:22
The error is expected, because the code is misusing the API. Specifically,

Connecting twice to the same schema is disallowed, unless the previous connection to the DB has been explicitly closed. Normally you would get a 113 error (see https://github.com/google/lovefield/blob/master/dist/error_code.json#L24). But because you are using a different schemaBuilder everytime, that check is not throwing, so you are hitting the next logical error, where you are trying to re-insert existing data in the database, and therefore it violates uniqueness constraints.

If you do need to re-initialize everything, the above is not  the right way. Instead try the following,
1) call db.close() on the 1st connection.
2) Re-use the same schemaBuillder object every time (no need to re-construct the schema).
3) Call connect() after the previous db connection has been closed.

**Comment by freshp86** [comment] 2016-04-21 17:28
BTW, since this is not a bug, I am closing the issue, please respond with additional questions at the discussion forum, https://groups.google.com/forum/#!forum/lovefield-users. Thanks.

**Closed by freshp86** 2016-04-21 17:28 UTC
