### ISSUE TITLE
Error on initial build - variable lf is undeclared in api_test.js

### ISSUE THREAD

**Issue by susanner23** [google/lovefield#114] opened 2015-11-23 00:17 UTC
<img width="422" alt="api_tester70error" src="https://cloud.githubusercontent.com/assets/4421705/11327239/ed519b56-91d3-11e5-984a-c6e3ab9b5274.png">

It looks like the files to include .lf were not included at the beginning of the test file.  I am more than happy to fix this one.

**Comment by arthurhsu** [comment] 2015-11-23 05:14
Please check your configuration. All our releases are verified by Travis CI and it does not show any issues. See https://travis-ci.org/google/lovefield/builds/92348023.

**Comment by susanner23** [comment] 2015-11-23 05:30
I'd like to contribute to this project.  Do you have any pointers on where I could begin?  I'm interested in adding some more included schemas that get added to lovefield on creation, like a schema for an audit trail log, which user could optionally turn on and pass parameters like username, ip address, table modified by user, previous value, value after change to store user actions and changes within their own application.

**Comment by arthurhsu** [comment] 2015-11-23 05:35
We have quite a few open issues there and there are specific ones marked as "helped wanted", which will be good starters for future contributors.

Also issues are for tracking Lovefield issues. Suggestions and discussions like this shall happen on public forum: https://groups.google.com/forum/#!forum/lovefield-users

**Comment by arthurhsu** [comment] 2015-11-23 08:30
Found minimum repro, it can only repro on Windows.

gulp build --filter=min_js

**Comment by susanner23** [comment] 2015-11-23 22:48
I added 

goog.require('lf.Type');
goog.require('lf.schema');

to api_tester.js   

guild build --filter=min_js  builds successfully now on Windows (64 bit). 

 Shall I submit pull request?

**Comment by freshp86** [comment] 2015-11-23 22:54
api_tester.js is supposed to load the lovefield.min.js binary such that it operates on the same binary that is distributed in the dist/ folder. No need for anything to be goog.required in this file, since all the dependencies are already in the min.js file.

The problem is that the externs (at https://github.com/google/lovefield/blob/master/dist/lovefield.externs.js) are not loaded properly which causes the compiler to throw an error).

**Closed** 2015-11-26 01:40 UTC
