### ISSUE TITLE
Constraint error: (201) Duplicate keys are not allowed

### ISSUE THREAD

**Issue by simonlast** [google/lovefield#155] opened 2016-05-19 18:31 UTC
I am writing some simple lovefield code, and in some cases the database seems to get corrupted and throw this error on startup: Constraint error: (201) Duplicate keys are not allowed.
The database is then corrupted until I clear it manually.

Connection:

			schemaBuilder.connect({
				storeType: storeType
			})
			.then((dbResult) => {
				console.log("connect: ", this.namespace, dbResult)
				this.db      = dbResult
				this.values  = this.db.getSchema().table(LocalStore.tableName)
				this.isReady = true
				this.readyEvents.emit("ready")
			})

Clear:

		this.db.delete().from(this.values).exec()

Multi-set:

					const setIds = {}
					const rows   = []
					// Use the rightmost value for duplicate keys.
					_.eachRight(requests, (request: LocalStoreRequest) => {
						if (request.type === LocalStoreRequestType.Set && !setIds[request.data.id]) {
							rows.push(this.values.createRow(request.data))
							setIds[request.data.id] = true
						}
					})
					if (rows.length > 0) {
						console.log("insertOrReplace: ", this.namespace, rows)
						return this.db.insertOrReplace().into(this.values).values(rows).exec()
					}

Multi-get:

				let ids = _.uniq(_.map(getRequests, "data"))
				if (ids.length > 0) {
					console.log("get: ", this.namespace, ids)
					return this.db.select().from(this.values).where(this.values.id.in(ids)).exec()
				}

The connection code is always run first, before any reads or writes. Reads and writes are run in batches, with writes first, and then reads.

I already ensure that no rows with duplicate keys are inserted during a read, so I'm not sure how it's possible to get this constraint error.

**Comment by freshp86** [comment] 2016-05-19 19:24
How does your schema look like? Can you post a minimal repro example?

BTW, I think we should improve the 201 error to provide more information (specifically to include the key that caused the error, will file a separate bug for this).

**Comment by freshp86** [comment] 2016-05-20 18:03
FYI, filed https://github.com/google/lovefield/issues/157, for improving the 201 error message.

**Comment by freshp86** [comment] 2016-05-20 18:58
Per https://github.com/google/lovefield/commit/490fde5f6b3dde50d8b51e27c9b7437ad4add530, the 201 error message has been updated to include additional information. I suggest trying the code that throws the 201 exception again with the Lovefield binaries from the master branch, to get more helpful error messages.

**Comment by simonlast** [comment] 2016-05-23 22:46
This is my schema:

			schemaBuilder.createTable(LocalStore.tableName)
				.addColumn("id", lf.Type.STRING)
				.addColumn("value", lf.Type.STRING)
				.addPrimaryKey(["id"])

**Comment by simonlast** [comment] 2016-05-23 22:46
Unfortunately I can't reproduce it consistently. It seems to happen when there are a lot of writes.

**Comment by arthurhsu** [comment] 2016-05-24 17:41
How's your read/write concurrency look like? Did you wait for the write transaction to finish before issuing another read? If your write transaction is not finished, the read transaction will read previous snapshot, and therefore duplicate keys are possible since you're not operating on your desired DB state.

**Comment by freshp86** [comment] 2016-05-24 18:05
If all queries are issued using Lovefield, waiting should not be a problem. Lovefield's transaction manager takes care of queuing transactions until they are ready to be executed. If a READ is issued while a WRITE is in progress, it will wait until the WRITE has finished before being executed.

**Comment by simonlast** [comment] 2016-05-24 18:36
Hmm, that could be the case, thanks.

**Comment by arthurhsu** [comment] 2016-05-25 03:00
Simon says he ensures no duplicate key himself, by reading the database after writing. What I meant is that he also needs to make sure the writing are committed, otherwise he'll get the previous snapshot of DB thinking he had everything written, and therefore causing 201.

This is explained in the transaction model of Lovefield, see https://github.com/google/lovefield/blob/master/docs/spec/05_transaction.md#53-explicit-transactions. This transaction model is consistent with most RDBMS in this world.

**Comment by freshp86** [comment] 2016-05-25 17:07
My understanding by reading the 1st comment was that 201 is thrown while connect() is running during index initialization, which would mean that somehow duplicate (corrupt) records had been persisted to disk in a previous run. If this is indeed happening then something is definitely wrong and is not just a case of misusing the transaction API.

This is hard to debug unless a minimal repro exists, even if it is not consistently reproducable, it would be very helpful.

**Comment by simonlast** [comment] 2016-05-28 00:31
Unfortunately I haven't been able to reproduce it again :(

**Comment by freshp86** [comment] 2016-05-28 00:41
I would say this is not unfortunate, it's good ;>

**Comment by freshp86** [comment] 2016-06-01 21:43
Closing this for now, since it can't be reproduced. Feel free to re-open if the problem comes back.

**Closed by freshp86** 2016-06-01 21:43 UTC

**Comment by mattblang** [comment] 2016-07-23 17:37
@simonlast Did it ever happen to you again? I am also seeing this periodically on startup in my Angular 2 app. I get the message: `Constraint error: (201) Duplicate keys are not allowed, index: , key:`.

**Comment by mattblang** [comment] 2016-07-23 18:44
@freshp86 @simonlast I am consistently seeing this happen when I first load my Angular 2 app; a refresh always fixes it. The message `Constraint error: (201) Duplicate keys are not allowed, index: , key:` appears to have blank entries for the `index` and `key` fields.

**Comment by simonlast** [comment] 2016-07-23 20:05
No unfortunately I decided not to use lovefield






On Sat, Jul 23, 2016 at 11:44 AM -0700, "Matt Langston" <notifications@github.com> wrote:












@freshp86 @simonlast I am consistently seeing this happen when I first load my Angular 2 app; a refresh always fixes it. The message Constraint error: (201) Duplicate keys are not allowed, index: , key: appears to have blank entries for the index and key fields.

**Comment by freshp86** [comment] 2016-07-25 17:11
@mattblang: Can you use debug version (lovefield.js), instead of lovefield.es6.js? This will make it clearer what is happening. Regarding the 201 exception, something seems definitely wrong, since the index's name should not be empty. The line that throws this error is at https://github.com/google/lovefield/blob/master/lib/index/btree.js#L1017.

Regarding the 2nd error, it is thrown by https://github.com/google/lovefield/blob/master/lib/backstore/indexed_db.js#L236, which also indicates that something is going wrong already (`this.db_` should not be undefined at that point).

Also can you use the regular lovefield binary lovefield.min.js instead of lovefield.es6.js and see if these errors are still happening?

**Comment by mattblang** [comment] 2016-07-26 23:48
@freshp86 That second error was one that I don't see frequently and just happened to notice while testing for the first error. I have switched to the debug version in case it happens again so I can post the more detailed stacktrace.

For the first error, it still occurs with the debug version and I know it was occurring with the regular binary as well; I had actually switched to the `es6` version to see if that might change anything.

In case it helps any, a pretty simple repository where this error is happening is located [here](https://github.com/mattblang/b4a), with most of the setup being [here](https://github.com/mattblang/b4a/blob/master/app/common/database.service.ts).

**Comment by freshp86** [comment] 2016-07-27 00:04
@mattblang : I am tying to reproduce the issue using the repository you linked. It seems some dependencies are missing from package.json? I am getting the following errors after running the scripts,

![image](https://cloud.githubusercontent.com/assets/7547039/17159552/f05a311e-5352-11e6-92fc-46ee72393deb.png)

**Comment by mattblang** [comment] 2016-07-27 01:41
@freshp86 That is very weird. `Chart.js` is a dependency for one of my explicit dependencies, `ng2-charts`. I just downloaded a `zip` of the `b4a` repo that I linked, ran `npm install`, and saw that the `chart.js` dependency was present.  An explicit `npm install charts.js@2.1.3` within the project folder will probably fix it. No clue why it didn't go grab it on `npm install`; what OS are you using?

**Comment by freshp86** [comment] 2016-07-27 02:06
Ok, I think the problem was caused by me running a very old version of NPM. I rerun the script with NPM 3.8.3 and I can load the page with no errors. So the next question is how do I reproduce the error? This is how the page looks like.

![image](https://cloud.githubusercontent.com/assets/7547039/17161649/156185fa-5364-11e6-9ce2-d4d473c01a90.png)

**Comment by mattblang** [comment] 2016-07-27 03:19
@freshp86 I can't get the error to occur until I add some test data by adding `one account` (just a name input), `one category` (just a name input), and then `one transaction` (just hit add without changing anything). After that, open a couple of new tabs to the `root site` (with the dashboard chart) and then the error should occur. It doesn't occur every time, but it should not take very many loads to cause it.

**Comment by freshp86** [comment] 2016-07-28 19:19
I was able to reproduce the error. There is a race condition at lines https://github.com/mattblang/b4a/blob/master/app/common/database.service.ts, lines 51 and 62, which results in  (sometimes)  calling `connect()` twice, which is an obvious error (causing the weird behavior).

Checking whether `this.database` is defined before calling connect is not enough, before line 51 might have already executed, but not resolved yet, so `this.database` is set after you already call the 2nd connect() at line 62.

A better way to resolve such race conditions is to store a promise as soon as you call connect() the first time (instead of relying on `this.database`). Sort of as follows
```
var whenDbConnectionReady_ = null;
...
whenDbConnectionReady_ = schemaBuilder.connect();
....
// later instead of checking for |this.database|, you check for |this.whenDbConnectionReady_ === null| // to avoid the race condition.
```

Having said all that, you need to be aware that Lovefield has a limitation when it comes to multiple tabs writing to the same IndexedDB, because all of in-memory data structures get out of sync. In other words this use case is not supported. This is recorded at https://github.com/google/lovefield/blob/master/docs/spec/99_postfix.md#multi-connection.

**Comment by mattblang** [comment] 2016-07-30 00:50
Ahhh, that makes sense. Thank you so very much @freshp86 !

**Comment by nbrustein** [comment] 2016-08-01 04:40
Note that there is a bit fuller discussion of the issues with multiple DB connections, and a kind of workaround, at https://github.com/google/lovefield/blob/master/docs/spec/03_life_of_db.md#32-multi-process-connection
