### ISSUE TITLE
Do not require schema object to be created every time

### ISSUE THREAD

**Issue by arthurhsu** [google/lovefield#64] opened 2015-08-14 18:46 UTC
Today we force the user to create schema object every time (either through SPAC or the schema builder). This part of code can be big in size especially when the user has many tables. Lovefield should be able to serialize the schema into persistent store and retrieve the schema from there.

**Comment by freshp86** [comment] 2015-09-09 20:36
Duplicate of https://github.com/google/lovefield/issues/58.

**Closed by freshp86** 2015-09-09 20:36 UTC
Labels: duplicate
