### ISSUE TITLE
Optimize join ordering in N-table joins where N > 2.

### ISSUE THREAD

**Issue by arthurhsu** [google/lovefield#4] opened 2014-10-01 21:02 UTC
order_by needs to be optimized
3-table join needs to be optimized

**Comment by freshp86** [comment] 2015-10-06 01:32
FYI, ORDER_BY is optimized (long time now), using the OrderByIndex optimization pass. I will rename this bug to better reflect what is left to do here.

**Comment by freshp86** [comment] 2015-10-06 22:18
Closing this one, since it is now a duplicate of https://github.com/google/lovefield/issues/41.

**Closed by freshp86** 2015-10-06 22:18 UTC
Labels: duplicate, performance
